name: "CHD Health Sign"

on: 
  schedule:
    - cron: "0 1 * * *" # scheduled at 07:00 (UTC+8) everyday
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/set-up-python@v3
        with:
          python-version: 3.8

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)

      - name: Run sign
        env:
          TOKEN: ${{ secrets.TOKEN }}
          LON: ${{ secrets.LON}}
          LAT: ${{ secrets.LAT}}
          ADDR: ${{ secrets.ADDR}}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 ./sign.py